#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""
__tt_argv=$(if [ $# -gt 0 ]; then for __tt_a in "$@"; do printf '%s\n' "$__tt_a"; done; fi)

repoRoot() {
  local __xcmd1="git rev-parse --show-toplevel 2>/dev/null"
  __xout2=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr3=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode4=0
  sh -c "$__xcmd1" >"$__xout2" 2>"$__xerr3" || __xcode4=$?
  __ret__code=$__xcode4
  __ret__stdout=$(cat "$__xout2" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr3" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout2" "$__xerr3"
  local __rec5__code="${__ret__code}"
  local __rec5__ok="${__ret__ok}"
  local __rec5__stdout="${__ret__stdout}"
  local __rec5__stderr="${__ret__stderr}"
  local r__code="${__rec5__code}"
  local r__ok="${__rec5__ok}"
  local r__stdout="${__rec5__stdout}"
  local r__stderr="${__rec5__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    printf '%s\n' "go-dev: not inside a git repository" 1>&2
    exit 1
  fi
  local __trim_s9="${r__stdout}"
  __trim8=$(__trim_s9="$__trim_s9" awk 'BEGIN { s = ENVIRON["__trim_s9"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  __ret=${__trim8}
  return 0
}

ensureUIEmbedDist() {
  local mairuDir="$1"
  local dist="${mairuDir}/ui/dist"
  local __p10="${dist}"
  mkdir -p -- "$__p10"
  local __ld_p13="${dist}"
  __ld_l14=$(ls -1 -A -- "$__ld_p13") || { printf 'tartalo: listDir: cannot list %s\n' "$__ld_p13" >&2; exit 1; }
  local entries="${__ld_l14}"
  local __s16="${entries}"
  if [ -z "$__s16" ]; then __len15=0; else __len15=$(printf '%s\n' "$__s16" | awk 'END{print NR}'); fi
  if [ "$__len15" -eq 0 ]; then
    local __wf_p17="${dist}/index.html"
    local __wf_c18="<!doctype html><meta charset=\"utf-8\"><title>mairu</title><!-- stub: run bun run build in mairu/ui -->
"
    printf '%s' "$__wf_c18" > "$__wf_p17" || { printf 'tartalo: writeFile: cannot write %s\n' "$__wf_p17" >&2; exit 1; }
  fi
}

listGoFiles() {
  local root="$1"
  local __xcmd19="git -C \"${root}\" ls-files -- '*.go'"
  __xout20=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr21=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode22=0
  sh -c "$__xcmd19" >"$__xout20" 2>"$__xerr21" || __xcode22=$?
  __ret__code=$__xcode22
  __ret__stdout=$(cat "$__xout20" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr21" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout20" "$__xerr21"
  local __rec23__code="${__ret__code}"
  local __rec23__ok="${__ret__ok}"
  local __rec23__stdout="${__ret__stdout}"
  local __rec23__stderr="${__ret__stderr}"
  local r__code="${__rec23__code}"
  local r__ok="${__rec23__ok}"
  local r__stdout="${__rec23__stdout}"
  local r__stderr="${__rec23__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    local __trim_s25="${r__stderr}"
    __trim24=$(__trim_s25="$__trim_s25" awk 'BEGIN { s = ENVIRON["__trim_s25"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim24}" 1>&2
    exit $((r__code))
  fi
  local __trim_s29="${r__stdout}"
  __trim28=$(__trim_s29="$__trim_s29" awk 'BEGIN { s = ENVIRON["__trim_s29"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local s="${__trim28}"
  if [ "${s}" = "" ]; then
    local empty=""
    __ret=${empty}
    return 0
  fi
  local __spl_s34="${s}"
  local __spl_d35="
"
  __spl33=$(__spl_s34="$__spl_s34" __spl_d35="$__spl_d35" awk 'BEGIN { s=ENVIRON["__spl_s34"]; d=ENVIRON["__spl_d35"]; if (d=="") { printf "%s", s; exit }; pos=1; dl=length(d); first=1; while(1) { rest=substr(s,pos); i=index(rest,d); if (i==0) { if (!first) printf "\n"; printf "%s", rest; exit }; if (!first) printf "\n"; printf "%s", substr(s,pos,i-1); pos=pos+i+dl-1; first=0 } }')
  __ret=${__spl33}
  return 0
}

runStream() {
  local cmd="$1"
  local __xcmd36="${cmd}"
  __xout37=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr38=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode39=0
  sh -c "$__xcmd36" >"$__xout37" 2>"$__xerr38" || __xcode39=$?
  __ret__code=$__xcode39
  __ret__stdout=$(cat "$__xout37" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr38" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout37" "$__xerr38"
  local __rec40__code="${__ret__code}"
  local __rec40__ok="${__ret__ok}"
  local __rec40__stdout="${__ret__stdout}"
  local __rec40__stderr="${__ret__stderr}"
  local r__code="${__rec40__code}"
  local r__ok="${__rec40__ok}"
  local r__stdout="${__rec40__stdout}"
  local r__stderr="${__rec40__stderr}"
  if [ "${r__stdout}" != "" ]; then
    printf '%s\n' "${r__stdout}"
  fi
  if [ "${r__stderr}" != "" ]; then
    printf '%s\n' "${r__stderr}" 1>&2
  fi
  __ret=$r__code
  return 0
}

mustRun() {
  local cmd="$1"
  runStream "${cmd}"
  local code="$__ret"
  if [ "$code" -ne 0 ]; then
    exit $((code))
  fi
}

quote() {
  local s="$1"
  __ret="\"${s}\""
  return 0
}

fmtGo() {
  local root="$1"
  printf '%s\n' "Formatting Go packages..."
  listGoFiles "${root}"
  local files="$__ret"
  local __s44="${files}"
  if [ -z "$__s44" ]; then __len43=0; else __len43=$(printf '%s\n' "$__s44" | awk 'END{print NR}'); fi
  if [ "$__len43" -eq 0 ]; then
    return 0
  fi
  local __map_a52="${files}"
  local __map_f53="quote"
  local __map_o54=""
  local __map_i55=1
  if [ -n "$__map_a52" ]; then
    while IFS= read -r __tt_iter; do
    "$__map_f53" "$__tt_iter"
    if [ "$__map_i55" = 1 ]; then __map_o54="$__ret"; __map_i55=0; else __map_o54=$(printf '%s\n%s' "$__map_o54" "$__ret"); fi
  done <<__TT_MAP_EOF__
$__map_a52
__TT_MAP_EOF__
  fi
  local __jn_s57="${__map_o54}"
  local __jn_d58=" "
  __jn56=$(__jn_s57="$__jn_s57" __jn_d58="$__jn_d58" awk 'BEGIN { s=ENVIRON["__jn_s57"]; d=ENVIRON["__jn_d58"]; if (s=="") exit; n=split(s, p, "\n"); for (i=1; i<=n; i++) { if (i>1) printf "%s", d; printf "%s", p[i] } }')
  local joined="${__jn56}"
  mustRun "cd \"${root}\" && gofmt -w ${joined}"
}

fmtCheckGo() {
  local root="$1"
  listGoFiles "${root}"
  local files="$__ret"
  local __s61="${files}"
  if [ -z "$__s61" ]; then __len60=0; else __len60=$(printf '%s\n' "$__s61" | awk 'END{print NR}'); fi
  if [ "$__len60" -eq 0 ]; then
    printf '%s\n' "No tracked Go files found."
    return 0
  fi
  local __map_a69="${files}"
  local __map_f70="quote"
  local __map_o71=""
  local __map_i72=1
  if [ -n "$__map_a69" ]; then
    while IFS= read -r __tt_iter; do
    "$__map_f70" "$__tt_iter"
    if [ "$__map_i72" = 1 ]; then __map_o71="$__ret"; __map_i72=0; else __map_o71=$(printf '%s\n%s' "$__map_o71" "$__ret"); fi
  done <<__TT_MAP_EOF__
$__map_a69
__TT_MAP_EOF__
  fi
  local __jn_s74="${__map_o71}"
  local __jn_d75=" "
  __jn73=$(__jn_s74="$__jn_s74" __jn_d75="$__jn_d75" awk 'BEGIN { s=ENVIRON["__jn_s74"]; d=ENVIRON["__jn_d75"]; if (s=="") exit; n=split(s, p, "\n"); for (i=1; i<=n; i++) { if (i>1) printf "%s", d; printf "%s", p[i] } }')
  local joined="${__jn73}"
  local __xcmd76="cd \"${root}\" && gofmt -l ${joined}"
  __xout77=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr78=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode79=0
  sh -c "$__xcmd76" >"$__xout77" 2>"$__xerr78" || __xcode79=$?
  __ret__code=$__xcode79
  __ret__stdout=$(cat "$__xout77" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr78" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout77" "$__xerr78"
  local __rec80__code="${__ret__code}"
  local __rec80__ok="${__ret__ok}"
  local __rec80__stdout="${__ret__stdout}"
  local __rec80__stderr="${__ret__stderr}"
  local r__code="${__rec80__code}"
  local r__ok="${__rec80__ok}"
  local r__stdout="${__rec80__stdout}"
  local r__stderr="${__rec80__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    local __trim_s82="${r__stderr}"
    __trim81=$(__trim_s82="$__trim_s82" awk 'BEGIN { s = ENVIRON["__trim_s82"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim81}" 1>&2
    exit $((r__code))
  fi
  local __trim_s86="${r__stdout}"
  __trim85=$(__trim_s86="$__trim_s86" awk 'BEGIN { s = ENVIRON["__trim_s86"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local bad="${__trim85}"
  if [ "${bad}" != "" ]; then
    printf '%s\n' "Go formatting check failed. Run: make fmt-go"
    local __spl_s88="${bad}"
    local __spl_d89="
"
    __spl87=$(__spl_s88="$__spl_s88" __spl_d89="$__spl_d89" awk 'BEGIN { s=ENVIRON["__spl_s88"]; d=ENVIRON["__spl_d89"]; if (d=="") { printf "%s", s; exit }; pos=1; dl=length(d); first=1; while(1) { rest=substr(s,pos); i=index(rest,d); if (i==0) { if (!first) printf "\n"; printf "%s", rest; exit }; if (!first) printf "\n"; printf "%s", substr(s,pos,i-1); pos=pos+i+dl-1; first=0 } }')
    local __lines90="${__spl87}"
    if [ -n "$__lines90" ]; then
      while IFS= read -r f; do
        printf '%s\n' " - ${f}"
      done <<__TARTALO_LINES__
$__lines90
__TARTALO_LINES__
    fi
    exit 1
  fi
  printf '%s\n' "Go formatting is clean."
}

lintGo() {
  local mairuDir="$1"
  ensureUIEmbedDist "${mairuDir}"
  local __xcmd91="command -v golangci-lint >/dev/null 2>&1"
  __xout92=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr93=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode94=0
  sh -c "$__xcmd91" >"$__xout92" 2>"$__xerr93" || __xcode94=$?
  __ret__code=$__xcode94
  __ret__stdout=$(cat "$__xout92" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr93" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout92" "$__xerr93"
  local __rec95__code="${__ret__code}"
  local __rec95__ok="${__ret__ok}"
  local __rec95__stdout="${__ret__stdout}"
  local __rec95__stderr="${__ret__stderr}"
  local have__code="${__rec95__code}"
  local have__ok="${__rec95__ok}"
  local have__stdout="${__rec95__stdout}"
  local have__stderr="${__rec95__stderr}"
  if [ "$have__ok" = 1 ]; then
    printf '%s\n' "Linting with golangci-lint..."
    mustRun "cd \"${mairuDir}\" && golangci-lint run ./..."
    return 0
  fi
  printf '%s\n' "golangci-lint not found, falling back to go vet."
  printf '%s\n' "Install with: go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest"
  mustRun "cd \"${mairuDir}\" && go vet ./..."
}

testGo() {
  local mairuDir="$1"
  ensureUIEmbedDist "${mairuDir}"
  printf '%s\n' "Running Go tests..."
  mustRun "cd \"${mairuDir}\" && go test ./..."
}

testRaceGo() {
  local mairuDir="$1"
  ensureUIEmbedDist "${mairuDir}"
  printf '%s\n' "Running Go tests with race detector..."
  mustRun "cd \"${mairuDir}\" && go test -race ./..."
}

coverageGo() {
  local mairuDir="$1"
  ensureUIEmbedDist "${mairuDir}"
  printf '%s\n' "Running Go coverage..."
  mustRun "cd \"${mairuDir}\" && go test -coverprofile=coverage.out ./... && go tool cover -func=coverage.out"
}

usage() {
  printf '%s\n' "Usage: go-dev.sh <command>"
  printf '%s\n' ""
  printf '%s\n' "Commands:"
  printf '%s\n' "  fmt        Format Go code"
  printf '%s\n' "  fmt-check  Verify gofmt cleanliness"
  printf '%s\n' "  lint       Run golangci-lint (or fallback go vet)"
  printf '%s\n' "  test       Run go test ./..."
  printf '%s\n' "  test-race  Run go test -race ./..."
  printf '%s\n' "  coverage   Run go test coverage and report"
  printf '%s\n' "  check      Run fmt-check + lint + tests"
  printf '%s\n' "  check-ci   Run fmt-check + lint + race tests"
}

main() {
  repoRoot
  local root="$__ret"
  local mairuDir="${root}/mairu"
  local argv="${__tt_argv}"
  local cmd=""
  local __s98="${argv}"
  if [ -z "$__s98" ]; then __len97=0; else __len97=$(printf '%s\n' "$__s98" | awk 'END{print NR}'); fi
  if [ "$__len97" -gt 0 ]; then
    __idx99=$(printf '%s' "${argv}" | awk -v i=0 'NR==i+1{print; exit}')
    cmd=${__idx99}
  fi
  local __subj100="${cmd}"
  case "$__subj100" in
    'fmt')
      fmtGo "${root}"
      ;;
    'fmt-check')
      fmtCheckGo "${root}"
      ;;
    'lint')
      lintGo "${mairuDir}"
      ;;
    'test')
      testGo "${mairuDir}"
      ;;
    'test-race')
      testRaceGo "${mairuDir}"
      ;;
    'coverage')
      coverageGo "${mairuDir}"
      ;;
    'check')
      fmtCheckGo "${root}"
      lintGo "${mairuDir}"
      testGo "${mairuDir}"
      ;;
    'check-ci')
      fmtCheckGo "${root}"
      lintGo "${mairuDir}"
      testRaceGo "${mairuDir}"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}


main "$@"
