#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""
__tt_argv=$(if [ $# -gt 0 ]; then for __tt_a in "$@"; do printf '%s\n' "$__tt_a"; done; fi)
__tt_request() {
  __tt_rq_url=$1; __tt_rq_method=$2; __tt_rq_body=$3; __tt_rq_timeout=$4
  __tt_rq_follow=$5; __tt_rq_insecure=$6; __tt_rq_user=$7; __tt_rq_pass=$8
  __tt_rq_hdrs=$9
  __tt_rq_btmp=$(mktemp 2>/dev/null || printf '/tmp/tt_rb_%s' "$$")
  __tt_rq_htmp=$(mktemp 2>/dev/null || printf '/tmp/tt_rh_%s' "$$")
  set --
  set -- "$@" -sS -X "$__tt_rq_method"
  if [ "$__tt_rq_follow" = 1 ]; then set -- "$@" -L; fi
  if [ "$__tt_rq_insecure" = 1 ]; then set -- "$@" -k; fi
  if [ "$__tt_rq_timeout" -gt 0 ] 2>/dev/null; then set -- "$@" --max-time "$__tt_rq_timeout"; fi
  if [ -n "$__tt_rq_user" ]; then set -- "$@" --user "$__tt_rq_user:$__tt_rq_pass"; fi
  if [ -n "$__tt_rq_body" ]; then set -- "$@" --data-binary "$__tt_rq_body"; fi
  if [ -n "$__tt_rq_hdrs" ]; then
    while IFS= read -r __tt_rq_h; do
      if [ -n "$__tt_rq_h" ]; then set -- "$@" -H "$__tt_rq_h"; fi
    done <<__TARTALO_REQ_HDRS__
$__tt_rq_hdrs
__TARTALO_REQ_HDRS__
  fi
  set -- "$@" -o "$__tt_rq_btmp" -D "$__tt_rq_htmp" -w '%{http_code}'
  __tt_rq_status=$(curl "$@" "$__tt_rq_url" 2>/dev/null) || __tt_rq_status=0
  __tt_rq_body_out=$(cat "$__tt_rq_btmp" 2>/dev/null || printf '')
  __tt_rq_hdrs_out=$(cat "$__tt_rq_htmp" 2>/dev/null || printf '')
  rm -f "$__tt_rq_btmp" "$__tt_rq_htmp"
  __ret__status=$__tt_rq_status
  __ret__body=$__tt_rq_body_out
  __ret__headers=$__tt_rq_hdrs_out
  __ret__ok=$(( __tt_rq_status >= 200 && __tt_rq_status < 300 ))
}

repoRoot() {
  local __xcmd1="git rev-parse --show-toplevel 2>/dev/null"
  __xout2=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr3=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode4=0
  sh -c "$__xcmd1" >"$__xout2" 2>"$__xerr3" || __xcode4=$?
  __ret__code=$__xcode4
  __ret__stdout=$(cat "$__xout2" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr3" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout2" "$__xerr3"
  local __rec5__code="${__ret__code}"
  local __rec5__ok="${__ret__ok}"
  local __rec5__stdout="${__ret__stdout}"
  local __rec5__stderr="${__ret__stderr}"
  local r__code="${__rec5__code}"
  local r__ok="${__rec5__ok}"
  local r__stdout="${__rec5__stdout}"
  local r__stderr="${__rec5__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    printf '%s\n' "meili-local: not inside a git repository" 1>&2
    exit 1
  fi
  local __trim_s9="${r__stdout}"
  __trim8=$(__trim_s9="$__trim_s9" awk 'BEGIN { s = ENVIRON["__trim_s9"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  __ret=${__trim8}
  return 0
}

detectAssetName() {
  local __xcmd10="uname -s"
  __xout11=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr12=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode13=0
  sh -c "$__xcmd10" >"$__xout11" 2>"$__xerr12" || __xcode13=$?
  __ret__code=$__xcode13
  __ret__stdout=$(cat "$__xout11" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr12" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout11" "$__xerr12"
  local __rec14__code="${__ret__code}"
  local __rec14__ok="${__ret__ok}"
  local __rec14__stdout="${__ret__stdout}"
  local __rec14__stderr="${__ret__stderr}"
  local osR__code="${__rec14__code}"
  local osR__ok="${__rec14__ok}"
  local osR__stdout="${__rec14__stdout}"
  local osR__stderr="${__rec14__stderr}"
  local __xcmd15="uname -m"
  __xout16=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr17=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode18=0
  sh -c "$__xcmd15" >"$__xout16" 2>"$__xerr17" || __xcode18=$?
  __ret__code=$__xcode18
  __ret__stdout=$(cat "$__xout16" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr17" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout16" "$__xerr17"
  local __rec19__code="${__ret__code}"
  local __rec19__ok="${__ret__ok}"
  local __rec19__stdout="${__ret__stdout}"
  local __rec19__stderr="${__ret__stderr}"
  local archR__code="${__rec19__code}"
  local archR__ok="${__rec19__ok}"
  local archR__stdout="${__rec19__stdout}"
  local archR__stderr="${__rec19__stderr}"
  local __trim_s21="${osR__stdout}"
  __trim20=$(__trim_s21="$__trim_s21" awk 'BEGIN { s = ENVIRON["__trim_s21"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local __trim_s23="${archR__stdout}"
  __trim22=$(__trim_s23="$__trim_s23" awk 'BEGIN { s = ENVIRON["__trim_s23"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local key="${__trim20}-${__trim22}"
  local __subj24="${key}"
  case "$__subj24" in
    'Darwin-arm64')
      __ret="meilisearch-macos-apple-silicon"
      return 0
      ;;
    'Darwin-x86_64')
      __ret="meilisearch-macos-amd64"
      return 0
      ;;
    'Linux-aarch64')
      __ret="meilisearch-linux-aarch64"
      return 0
      ;;
    'Linux-arm64')
      __ret="meilisearch-linux-aarch64"
      return 0
      ;;
    'Linux-x86_64')
      __ret="meilisearch-linux-amd64"
      return 0
      ;;
    *)
      printf '%s\n' "Unsupported platform: ${key}" 1>&2
      exit 1
      ;;
  esac
  __ret=""
  return 0
}

toolsDirOf() {
  local root="$1"
  __ret="${root}/.tools/meilisearch"
  return 0
}

dataDirOf() {
  local root="$1"
  __ret="${root}/.data/meilisearch"
  return 0
}

logDirOf() {
  local root="$1"
  __ret="${root}/.logs"
  return 0
}

pidFileOf() {
  local root="$1"
  toolsDirOf "${root}"
  local __ret25="$__ret"
  __ret="${__ret25}/meilisearch.pid"
  return 0
}

versionFileOf() {
  local root="$1"
  toolsDirOf "${root}"
  local __ret26="$__ret"
  __ret="${__ret26}/version.txt"
  return 0
}

meiliBinOf() {
  local root="$1"
  toolsDirOf "${root}"
  local __ret27="$__ret"
  __ret="${__ret27}/meilisearch"
  return 0
}

logFileOf() {
  local root="$1"
  logDirOf "${root}"
  local __ret28="$__ret"
  __ret="${__ret28}/meilisearch.log"
  return 0
}

meiliVersion() {
  local __envname31="MEILI_VERSION"
  case "$__envname31" in ''|[!A-Za-z_]*|*[!A-Za-z0-9_]*) __env29=""; __envn30=1 ;; *) eval "__envset32=\${$__envname31+1}"; if [ -z "$__envset32" ]; then __env29=""; __envn30=1; else eval "__env29=\$$__envname31"; __envn30=0; fi ;; esac
  if [ "$__envn30" = 1 ]; then __co33="v1.12.3"; else __co33="${__env29}"; fi
  __ret=${__co33}
  return 0
}

meiliHost() {
  local __envname36="MEILI_HOST"
  case "$__envname36" in ''|[!A-Za-z_]*|*[!A-Za-z0-9_]*) __env34=""; __envn35=1 ;; *) eval "__envset37=\${$__envname36+1}"; if [ -z "$__envset37" ]; then __env34=""; __envn35=1; else eval "__env34=\$$__envname36"; __envn35=0; fi ;; esac
  if [ "$__envn35" = 1 ]; then __co38="127.0.0.1"; else __co38="${__env34}"; fi
  __ret=${__co38}
  return 0
}

meiliPort() {
  local __envname41="MEILI_PORT"
  case "$__envname41" in ''|[!A-Za-z_]*|*[!A-Za-z0-9_]*) __env39=""; __envn40=1 ;; *) eval "__envset42=\${$__envname41+1}"; if [ -z "$__envset42" ]; then __env39=""; __envn40=1; else eval "__env39=\$$__envname41"; __envn40=0; fi ;; esac
  if [ "$__envn40" = 1 ]; then __co43="7700"; else __co43="${__env39}"; fi
  __ret=${__co43}
  return 0
}

meiliApiKey() {
  local __envname46="MEILI_API_KEY"
  case "$__envname46" in ''|[!A-Za-z_]*|*[!A-Za-z0-9_]*) __env44=""; __envn45=1 ;; *) eval "__envset47=\${$__envname46+1}"; if [ -z "$__envset47" ]; then __env44=""; __envn45=1; else eval "__env44=\$$__envname46"; __envn45=0; fi ;; esac
  if [ "$__envn45" = 1 ]; then __co48="contextfs-dev-key"; else __co48="${__env44}"; fi
  __ret=${__co48}
  return 0
}

meiliURL() {
  meiliHost
  local __ret49="$__ret"
  meiliPort
  local __ret50="$__ret"
  __ret="http://${__ret49}:${__ret50}"
  return 0
}

healthURL() {
  meiliURL
  local __ret51="$__ret"
  __ret="${__ret51}/health"
  return 0
}

isRunning() {
  local pidFile="$1"
  local __fst_p52="${pidFile}"
  if [ -f "$__fst_p52" ]; then __fst_r53=1; else __fst_r53=0; fi
  __cond54=$((__fst_r53))
  if ! [ "$__cond54" = 1 ]; then
    __ret=0
    return 0
  fi
  local __rf_p59="${pidFile}"
  __rf_c60=$(cat -- "$__rf_p59") || { printf 'tartalo: readFile: cannot read %s\n' "$__rf_p59" >&2; exit 1; }
  local __trim_s62="${__rf_c60}"
  __trim61=$(__trim_s62="$__trim_s62" awk 'BEGIN { s = ENVIRON["__trim_s62"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local pid="${__trim61}"
  if [ "${pid}" = "" ]; then
    __ret=0
    return 0
  fi
  local __xcmd63="kill -0 ${pid} >/dev/null 2>&1"
  __xout64=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr65=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode66=0
  sh -c "$__xcmd63" >"$__xout64" 2>"$__xerr65" || __xcode66=$?
  __ret__code=$__xcode66
  __ret__stdout=$(cat "$__xout64" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr65" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout64" "$__xerr65"
  local __rec67__code="${__ret__code}"
  local __rec67__ok="${__ret__ok}"
  local __rec67__stdout="${__ret__stdout}"
  local __rec67__stderr="${__ret__stderr}"
  local r__code="${__rec67__code}"
  local r__ok="${__rec67__ok}"
  local r__stdout="${__rec67__stdout}"
  local r__stderr="${__rec67__stderr}"
  __ret=$r__ok
  return 0
}

downloadMeili() {
  local root="$1"
  toolsDirOf "${root}"
  local toolsDir="$__ret"
  meiliBinOf "${root}"
  local meiliBin="$__ret"
  versionFileOf "${root}"
  local versionFile="$__ret"
  meiliVersion
  local version="$__ret"
  detectAssetName
  local asset="$__ret"
  local url="https://github.com/meilisearch/meilisearch/releases/download/${version}/${asset}"
  local __p73="${toolsDir}"
  mkdir -p -- "$__p73"
  local __fst_p74="${meiliBin}"
  if [ -f "$__fst_p74" ]; then __fst_r75=1; else __fst_r75=0; fi
  __cond76=$((__fst_r75))
  local __fst_p77="${versionFile}"
  if [ -f "$__fst_p77" ]; then __fst_r78=1; else __fst_r78=0; fi
  __cond79=$((__fst_r78))
  if { [ "$__cond76" = 1 ]; } && { [ "$__cond79" = 1 ]; }; then
    local __rf_p80="${versionFile}"
    __rf_c81=$(cat -- "$__rf_p80") || { printf 'tartalo: readFile: cannot read %s\n' "$__rf_p80" >&2; exit 1; }
    local __trim_s83="${__rf_c81}"
    __trim82=$(__trim_s83="$__trim_s83" awk 'BEGIN { s = ENVIRON["__trim_s83"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    if [ "${__trim82}" = "${version}" ]; then
      return 0
    fi
  fi
  printf '%s\n' "Downloading Meilisearch ${version} (${asset})..."
  local __xcmd84="curl -fL \"${url}\" -o \"${meiliBin}\""
  __xout85=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr86=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode87=0
  sh -c "$__xcmd84" >"$__xout85" 2>"$__xerr86" || __xcode87=$?
  __ret__code=$__xcode87
  __ret__stdout=$(cat "$__xout85" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr86" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout85" "$__xerr86"
  local __rec88__code="${__ret__code}"
  local __rec88__ok="${__ret__ok}"
  local __rec88__stdout="${__ret__stdout}"
  local __rec88__stderr="${__ret__stderr}"
  local r__code="${__rec88__code}"
  local r__ok="${__rec88__ok}"
  local r__stdout="${__rec88__stdout}"
  local r__stderr="${__rec88__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    local __trim_s90="${r__stderr}"
    __trim89=$(__trim_s90="$__trim_s90" awk 'BEGIN { s = ENVIRON["__trim_s90"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim89}" 1>&2
    exit $((r__code))
  fi
  local __xcmd91="chmod +x \"${meiliBin}\""
  __xout92=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr93=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode94=0
  sh -c "$__xcmd91" >"$__xout92" 2>"$__xerr93" || __xcode94=$?
  __ret__code=$__xcode94
  __ret__stdout=$(cat "$__xout92" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr93" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout92" "$__xerr93"
  local __rec95__code="${__ret__code}"
  local __rec95__ok="${__ret__ok}"
  local __rec95__stdout="${__ret__stdout}"
  local __rec95__stderr="${__ret__stderr}"
  local chmodR__code="${__rec95__code}"
  local chmodR__ok="${__rec95__ok}"
  local chmodR__stdout="${__rec95__stdout}"
  local chmodR__stderr="${__rec95__stderr}"
  if ! [ "$chmodR__ok" = 1 ]; then
    local __trim_s97="${chmodR__stderr}"
    __trim96=$(__trim_s97="$__trim_s97" awk 'BEGIN { s = ENVIRON["__trim_s97"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim96}" 1>&2
    exit $((chmodR__code))
  fi
  local __wf_p98="${versionFile}"
  local __wf_c99="${version}"
  printf '%s' "$__wf_c99" > "$__wf_p98" || { printf 'tartalo: writeFile: cannot write %s\n' "$__wf_p98" >&2; exit 1; }
}

waitForHealth() {
  local root="$1"
  healthURL
  local url="$__ret"
  local i=0
  while [ "$i" -lt 30 ]; do
    local __ftu101="${url}"
    local __fts102=2
    __tt_request "$__ftu101" 'GET' '' "$__fts102" 1 0 '' '' ''
    local __rec103__status="${__ret__status}"
    local __rec103__ok="${__ret__ok}"
    local __rec103__body="${__ret__body}"
    local __rec103__headers="${__ret__headers}"
    local r__status="${__rec103__status}"
    local r__ok="${__rec103__ok}"
    local r__body="${__rec103__body}"
    local r__headers="${__rec103__headers}"
    if [ "$r__ok" = 1 ]; then
      return 0
    fi
    sleep 1
    i=$((i + 1))
  done
  logFileOf "${root}"
  local __ret104="$__ret"
  printf '%s\n' "Meilisearch did not become healthy in time. Check ${__ret104}" 1>&2
  exit 1
}

startMeili() {
  local root="$1"
  dataDirOf "${root}"
  local __ret105="$__ret"
  local __p106="${__ret105}"
  mkdir -p -- "$__p106"
  logDirOf "${root}"
  local __ret107="$__ret"
  local __p108="${__ret107}"
  mkdir -p -- "$__p108"
  toolsDirOf "${root}"
  local __ret109="$__ret"
  local __p110="${__ret109}"
  mkdir -p -- "$__p110"
  downloadMeili "${root}"
  pidFileOf "${root}"
  local pidFile="$__ret"
  meiliURL
  local url="$__ret"
  isRunning "${pidFile}"
  local __ret113="$__ret"
  __cond114=$((__ret113))
  if [ "$__cond114" = 1 ]; then
    printf '%s\n' "Meilisearch is already running at ${url}"
    return 0
  fi
  printf '%s\n' "Starting Meilisearch at ${url}"
  meiliBinOf "${root}"
  local __ret115="$__ret"
  meiliHost
  local __ret116="$__ret"
  meiliPort
  local __ret117="$__ret"
  meiliApiKey
  local __ret118="$__ret"
  dataDirOf "${root}"
  local __ret119="$__ret"
  logFileOf "${root}"
  local __ret120="$__ret"
  local cmd="nohup \"${__ret115}\" --http-addr \"${__ret116}:${__ret117}\" --master-key \"${__ret118}\" --db-path \"${__ret119}\" > \"${__ret120}\" 2>&1 & echo \$! > \"${pidFile}\""
  local __xcmd121="${cmd}"
  __xout122=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr123=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode124=0
  sh -c "$__xcmd121" >"$__xout122" 2>"$__xerr123" || __xcode124=$?
  __ret__code=$__xcode124
  __ret__stdout=$(cat "$__xout122" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr123" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout122" "$__xerr123"
  local __rec125__code="${__ret__code}"
  local __rec125__ok="${__ret__ok}"
  local __rec125__stdout="${__ret__stdout}"
  local __rec125__stderr="${__ret__stderr}"
  local r__code="${__rec125__code}"
  local r__ok="${__rec125__ok}"
  local r__stdout="${__rec125__stdout}"
  local r__stderr="${__rec125__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    local __trim_s127="${r__stderr}"
    __trim126=$(__trim_s127="$__trim_s127" awk 'BEGIN { s = ENVIRON["__trim_s127"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim126}" 1>&2
    exit $((r__code))
  fi
  waitForHealth "${root}"
  printf '%s\n' "Meilisearch is healthy at ${url}"
}

stopMeili() {
  local root="$1"
  pidFileOf "${root}"
  local pidFile="$__ret"
  isRunning "${pidFile}"
  local __ret129="$__ret"
  __cond130=$((__ret129))
  if ! [ "$__cond130" = 1 ]; then
    printf '%s\n' "Meilisearch is not running"
    local __p131="${pidFile}"
    rm -f -- "$__p131"
    return 0
  fi
  local __rf_p136="${pidFile}"
  __rf_c137=$(cat -- "$__rf_p136") || { printf 'tartalo: readFile: cannot read %s\n' "$__rf_p136" >&2; exit 1; }
  local __trim_s139="${__rf_c137}"
  __trim138=$(__trim_s139="$__trim_s139" awk 'BEGIN { s = ENVIRON["__trim_s139"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local pid="${__trim138}"
  printf '%s\n' "Stopping Meilisearch (pid ${pid})..."
  local __xcmd140="kill ${pid} >/dev/null 2>&1 || true"
  __xout141=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr142=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode143=0
  sh -c "$__xcmd140" >"$__xout141" 2>"$__xerr142" || __xcode143=$?
  __ret__code=$__xcode143
  __ret__stdout=$(cat "$__xout141" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr142" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout141" "$__xerr142"
  local __rec144__code="${__ret__code}"
  local __rec144__ok="${__ret__ok}"
  local __rec144__stdout="${__ret__stdout}"
  local __rec144__stderr="${__ret__stderr}"
  local __p145="${pidFile}"
  rm -f -- "$__p145"
}

statusMeili() {
  local root="$1"
  pidFileOf "${root}"
  local pidFile="$__ret"
  isRunning "${pidFile}"
  local __ret147="$__ret"
  __cond148=$((__ret147))
  if [ "$__cond148" = 1 ]; then
    local __rf_p149="${pidFile}"
    __rf_c150=$(cat -- "$__rf_p149") || { printf 'tartalo: readFile: cannot read %s\n' "$__rf_p149" >&2; exit 1; }
    local __trim_s152="${__rf_c150}"
    __trim151=$(__trim_s152="$__trim_s152" awk 'BEGIN { s = ENVIRON["__trim_s152"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    meiliURL
    local __ret153="$__ret"
    printf '%s\n' "Meilisearch is running (pid ${__trim151}) at ${__ret153}"
  else
    printf '%s\n' "Meilisearch is stopped"
  fi
}

cleanMeili() {
  local root="$1"
  stopMeili "${root}"
  dataDirOf "${root}"
  local __ret154="$__ret"
  logFileOf "${root}"
  local __ret155="$__ret"
  local __xcmd156="rm -rf \"${__ret154}\" \"${__ret155}\""
  __xout157=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr158=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode159=0
  sh -c "$__xcmd156" >"$__xout157" 2>"$__xerr158" || __xcode159=$?
  __ret__code=$__xcode159
  __ret__stdout=$(cat "$__xout157" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr158" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout157" "$__xerr158"
  local __rec160__code="${__ret__code}"
  local __rec160__ok="${__ret__ok}"
  local __rec160__stdout="${__ret__stdout}"
  local __rec160__stderr="${__ret__stderr}"
  printf '%s\n' "Deleted local Meilisearch data and logs"
}

usage() {
  printf '%s\n' "Usage: mairu/scripts/meili-local.sh <command>"
  printf '%s\n' ""
  printf '%s\n' "Commands:"
  printf '%s\n' "  up      Download (if needed) and start Meilisearch locally"
  printf '%s\n' "  down    Stop local Meilisearch"
  printf '%s\n' "  status  Print Meilisearch status"
  printf '%s\n' "  clean   Stop Meilisearch and delete local data/logs"
}

main() {
  repoRoot
  local root="$__ret"
  local argv="${__tt_argv}"
  local cmd=""
  local __s163="${argv}"
  if [ -z "$__s163" ]; then __len162=0; else __len162=$(printf '%s\n' "$__s163" | awk 'END{print NR}'); fi
  if [ "$__len162" -gt 0 ]; then
    __idx164=$(printf '%s' "${argv}" | awk -v i=0 'NR==i+1{print; exit}')
    cmd=${__idx164}
  fi
  local __subj165="${cmd}"
  case "$__subj165" in
    'up')
      startMeili "${root}"
      ;;
    'down')
      stopMeili "${root}"
      ;;
    'status')
      statusMeili "${root}"
      ;;
    'clean')
      cleanMeili "${root}"
      ;;
    *)
      usage
      exit 1
      ;;
  esac
}


main "$@"
