// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyMemoryFeedback(arg1, arg2) {
  return window['go']['desktop']['App']['ApplyMemoryFeedback'](arg1, arg2);
}

export function ApproveAction(arg1, arg2) {
  return window['go']['desktop']['App']['ApproveAction'](arg1, arg2);
}

export function BuildMenu() {
  return window['go']['desktop']['App']['BuildMenu']();
}

export function ClusterStats() {
  return window['go']['desktop']['App']['ClusterStats']();
}

export function CreateContextNode(arg1) {
  return window['go']['desktop']['App']['CreateContextNode'](arg1);
}

export function CreateMemory(arg1) {
  return window['go']['desktop']['App']['CreateMemory'](arg1);
}

export function CreateSession(arg1) {
  return window['go']['desktop']['App']['CreateSession'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['desktop']['App']['CreateSkill'](arg1);
}

export function Dashboard(arg1, arg2) {
  return window['go']['desktop']['App']['Dashboard'](arg1, arg2);
}

export function DeleteContextNode(arg1) {
  return window['go']['desktop']['App']['DeleteContextNode'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['desktop']['App']['DeleteMemory'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['desktop']['App']['DeleteSkill'](arg1);
}

export function ExportData(arg1) {
  return window['go']['desktop']['App']['ExportData'](arg1);
}

export function Health() {
  return window['go']['desktop']['App']['Health']();
}

export function ImportData() {
  return window['go']['desktop']['App']['ImportData']();
}

export function ListContextNodes(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['ListContextNodes'](arg1, arg2, arg3);
}

export function ListMemories(arg1, arg2) {
  return window['go']['desktop']['App']['ListMemories'](arg1, arg2);
}

export function ListModerationQueue(arg1) {
  return window['go']['desktop']['App']['ListModerationQueue'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function ListSkills(arg1, arg2) {
  return window['go']['desktop']['App']['ListSkills'](arg1, arg2);
}

export function LoadSessionHistory(arg1) {
  return window['go']['desktop']['App']['LoadSessionHistory'](arg1);
}

export function LoadWindowState() {
  return window['go']['desktop']['App']['LoadWindowState']();
}

export function Ping() {
  return window['go']['desktop']['App']['Ping']();
}

export function ReviewModeration(arg1) {
  return window['go']['desktop']['App']['ReviewModeration'](arg1);
}

export function SaveWindowState() {
  return window['go']['desktop']['App']['SaveWindowState']();
}

export function Search(arg1) {
  return window['go']['desktop']['App']['Search'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['desktop']['App']['SendMessage'](arg1, arg2);
}

export function SetupTray() {
  return window['go']['desktop']['App']['SetupTray']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['desktop']['App']['ShowNotification'](arg1, arg2);
}

export function UpdateContextNode(arg1) {
  return window['go']['desktop']['App']['UpdateContextNode'](arg1);
}

export function UpdateMemory(arg1) {
  return window['go']['desktop']['App']['UpdateMemory'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['desktop']['App']['UpdateSkill'](arg1);
}

export function VibeMutationExecute(arg1, arg2) {
  return window['go']['desktop']['App']['VibeMutationExecute'](arg1, arg2);
}

export function VibeMutationPlan(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['VibeMutationPlan'](arg1, arg2, arg3);
}

export function VibeQuery(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['VibeQuery'](arg1, arg2, arg3);
}
