// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {contextsrv} from '../models';
import {menu} from '../models';
import {agent} from '../models';
import {desktop} from '../models';

export function ApplyMemoryFeedback(arg1:string,arg2:number):Promise<contextsrv.Memory>;

export function ApproveAction(arg1:string,arg2:boolean):Promise<void>;

export function BuildMenu():Promise<menu.Menu>;

export function ClusterStats():Promise<Record<string, any>>;

export function CreateContextNode(arg1:contextsrv.ContextCreateInput):Promise<contextsrv.ContextNode>;

export function CreateMemory(arg1:contextsrv.MemoryCreateInput):Promise<contextsrv.Memory>;

export function CreateSession(arg1:string):Promise<void>;

export function CreateSkill(arg1:contextsrv.SkillCreateInput):Promise<contextsrv.Skill>;

export function Dashboard(arg1:number,arg2:string):Promise<Record<string, any>>;

export function DeleteContextNode(arg1:string):Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function ExportData(arg1:string):Promise<void>;

export function Health():Promise<Record<string, any>>;

export function ImportData():Promise<void>;

export function ListContextNodes(arg1:string,arg2:any,arg3:number):Promise<Array<contextsrv.ContextNode>>;

export function ListMemories(arg1:string,arg2:number):Promise<Array<contextsrv.Memory>>;

export function ListModerationQueue(arg1:number):Promise<Array<contextsrv.ModerationEvent>>;

export function ListSessions():Promise<Array<string>>;

export function ListSkills(arg1:string,arg2:number):Promise<Array<contextsrv.Skill>>;

export function LoadSessionHistory(arg1:string):Promise<Array<agent.SavedMessage>>;

export function LoadWindowState():Promise<desktop.WindowState>;

export function Ping():Promise<string>;

export function ReviewModeration(arg1:contextsrv.ModerationReviewInput):Promise<void>;

export function SaveWindowState():Promise<void>;

export function Search(arg1:contextsrv.SearchOptions):Promise<Record<string, any>>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetupTray():Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function UpdateContextNode(arg1:contextsrv.ContextUpdateInput):Promise<contextsrv.ContextNode>;

export function UpdateMemory(arg1:contextsrv.MemoryUpdateInput):Promise<contextsrv.Memory>;

export function UpdateSkill(arg1:contextsrv.SkillUpdateInput):Promise<contextsrv.Skill>;

export function VibeMutationExecute(arg1:Array<contextsrv.VibeMutationOp>,arg2:string):Promise<Array<Record<string, any>>>;

export function VibeMutationPlan(arg1:string,arg2:string,arg3:number):Promise<contextsrv.VibeMutationPlan>;

export function VibeQuery(arg1:string,arg2:string,arg3:number):Promise<contextsrv.VibeQueryResult>;
