#!/usr/bin/env node
// Concatenates lib/*.js ES modules into content.js, stripping import/export so
// the result can run as a classic content script (no module support in MV3 content).

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');

const LIBS = [
  'lib/dom.js',
  'lib/overlay.js',
  'lib/hydration.js',
  'lib/serializer.js',
];

function stripModuleSyntax(src) {
  return src
    .replace(/^\s*import\s+[^;]+;?\s*$/gm, '')
    .replace(/^\s*export\s+default\s+/gm, 'const __default = ')
    .replace(/^\s*export\s+(async\s+)?function(\*?)\s+/gm, '$1function$2 ')
    .replace(/^\s*export\s+(class|const|let|var)\s+/gm, '$1 ')
    .replace(/^\s*export\s*\{[^}]*\}\s*;?\s*$/gm, '');
}

const banner = `// GENERATED by scripts/build-content.mjs — do not edit directly.\n// Edit content.src.js or lib/*.js and rerun 'bun run build:content'.\n`;

const libBlob = LIBS.map((p) => {
  const body = fs.readFileSync(path.join(ROOT, p), 'utf8');
  return `// ==== ${p} ====\n${stripModuleSyntax(body)}\n`;
}).join('\n');

const main = fs.readFileSync(path.join(ROOT, 'content.src.js'), 'utf8');
const stripped = stripModuleSyntax(main);
fs.writeFileSync(path.join(ROOT, 'content.js'), `${banner}\n${libBlob}\n${stripped}`);
console.log('wrote content.js');
