// GENERATED by scripts/build-content.mjs — do not edit directly.
// Edit content.src.js or lib/*.js and rerun 'bun run build:content'.

// ==== lib/dom.js ====
function getCssSelector(el) {
  if (!el || el.nodeType !== 1) return '';
  const path = [];
  while (el && el.nodeType === 1) {
    if (el.id) {
      path.unshift('#' + cssEscape(el.id));
      break;
    }
    let selector = el.localName;
    let sib = el;
    let nth = 1;
    while ((sib = sib.previousElementSibling)) {
      if (sib.localName === el.localName) nth++;
    }
    if (nth !== 1) selector += `:nth-of-type(${nth})`;
    path.unshift(selector);
    const parent = el.parentNode;
    if (!parent) break;
    // Walk past shadow-root boundaries
    if (parent.host) {
      el = parent.host;
      continue;
    }
    if (parent === parent.ownerDocument) break;
    el = parent;
  }
  return path.join(' > ');
}

function cssEscape(s) {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(s);
  return String(s).replace(/[^a-zA-Z0-9_-]/g, (c) => `\\${c}`);
}

function getShadowRoot(el) {
  if (typeof chrome !== 'undefined' && chrome.dom && typeof chrome.dom.openOrClosedShadowRoot === 'function') {
    try { return chrome.dom.openOrClosedShadowRoot(el); } catch (err) { void err; }
  }
  return el.shadowRoot || null;
}
function* walkShadowRoots(root) {
  const stack = [root];
  while (stack.length) {
    const node = stack.pop();
    if (!node || !node.querySelectorAll) continue;
    for (const el of node.querySelectorAll('*')) {
      const sr = getShadowRoot(el);
      if (sr) {
        yield sr;
        stack.push(sr);
      }
    }
  }
}
function querySelectorDeep(root, selector) {
  if (!root) return null;
  if (root.querySelector) {
    const found = root.querySelector(selector);
    if (found) return found;
  }
  for (const r of walkShadowRoots(root)) {
    const hit = r.querySelector(selector);
    if (hit) return hit;
  }
  return null;
}
function querySelectorAllDeep(root, selector, limit = 1000) {
  const out = [];
  const visit = (n) => {
    if (out.length >= limit || !n.querySelectorAll) return;
    for (const el of n.querySelectorAll(selector)) {
      if (out.length >= limit) return;
      out.push(el);
    }
  };
  visit(root);
  for (const r of walkShadowRoots(root)) visit(r);
  return out;
}
function rafBatch(fn) {
  let scheduled = false;
  return function () {
    if (scheduled) return;
    scheduled = true;
    const raf = typeof requestAnimationFrame === 'function' ? requestAnimationFrame : (cb) => setTimeout(cb, 16);
    raf(() => {
      scheduled = false;
      try { fn(); } catch (err) { void err; }
    });
  };
}
function isVisible(el) {
  try {
    const s = getComputedStyle(el);
    return s.display !== 'none' && s.visibility !== 'hidden' && s.opacity !== '0';
  } catch (err) {
    void err;
    return true;
  }
}


// ==== lib/overlay.js ====
const TAG = 'mairu-overlay';
const STYLE = `
  :host { all: initial; position: fixed; bottom: 20px; right: 20px;
          z-index: 2147483647; pointer-events: none;
          font: 14px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  .card { max-width: 300px; background: #1e1e1e; color: #fff;
          border: 1px solid #333; border-radius: 8px; padding: 12px 16px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
          opacity: 0; transform: translateY(10px);
          transition: opacity .2s ease, transform .2s ease; }
  .card.visible { opacity: 1; transform: translateY(0); }
  .row { display: flex; align-items: flex-start; gap: 10px; }
  .icon { font-size: 18px; }
`;

function define() {
  if (typeof customElements === 'undefined' || customElements === null) return;
  if (customElements.get(TAG)) return;
  class MairuOverlay extends HTMLElement {
    connectedCallback() {
      if (this._shadow) return;
      const root = this.attachShadow({ mode: 'closed' });
      root.innerHTML = `<style>${STYLE}</style>
        <div class="card"><div class="row"><div class="icon">🤖</div><div class="text"></div></div></div>`;
      this._root = root;
      this._card = root.querySelector('.card');
      this._text = root.querySelector('.text');
      this._shadow = true;
    }
    show(t) {
      if (!this._text) return;
      this._text.textContent = t;
      this._card.classList.add('visible');
    }
    hide() {
      if (!this._card) return;
      this._card.classList.remove('visible');
    }
    // For tests — exposes a shadow node reference without breaking encapsulation in prod.
    _testShadow() {
      return this._root;
    }
  }
  customElements.define(TAG, MairuOverlay);
}
function installOverlay(doc = document) {
  define();
  let el = doc.querySelector(TAG);
  if (!el) {
    el = doc.createElement(TAG);
    (doc.documentElement || doc.body).appendChild(el);
  }
  return {
    showThought: (t) => el.show && el.show(t),
    hideThought: () => el.hide && el.hide(),
    destroy: () => { el.remove(); },
    _element: el,
  };
}


// ==== lib/selection-prompt.js ====
// Floating "Ask Mairu" affordance shown on text selection.
// On click, opens a small composer near the selection where the user can
// type an extra prompt; submit hands {selection, prompt, url, title} to
// the service worker via chrome.runtime.sendMessage({type:'send_to_agent'}).

const HOST_TAG = 'mairu-selection-prompt';
const MIN_SELECTION_LEN = 3;
const MAX_PREVIEW_LEN = 280;

const STYLE = `
  :host { all: initial; position: absolute; z-index: 2147483647;
          font: 13px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          color: #111827; }
  .pill {
    display: inline-flex; align-items: center; gap: 6px;
    background: #2563eb; color: #fff; border: none; border-radius: 999px;
    padding: 6px 12px; cursor: pointer; box-shadow: 0 4px 12px rgba(0,0,0,0.18);
    font-size: 12px; font-weight: 500;
  }
  .pill:hover { background: #1d4ed8; }
  .panel {
    width: 320px; background: #fff; border: 1px solid #e5e7eb; border-radius: 10px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.18); overflow: hidden;
  }
  .panel header {
    display: flex; align-items: center; justify-content: space-between;
    padding: 8px 12px; border-bottom: 1px solid #f3f4f6;
    font-weight: 600; color: #2563eb; font-size: 12px;
  }
  .panel header button {
    background: none; border: none; cursor: pointer; color: #9ca3af; font-size: 16px;
    line-height: 1; padding: 0;
  }
  .panel .preview {
    font-size: 11px; color: #6b7280; padding: 6px 12px; max-height: 64px; overflow: hidden;
    border-bottom: 1px dashed #f3f4f6; background: #fafbfc; white-space: pre-wrap;
  }
  .panel textarea {
    width: 100%; min-height: 70px; max-height: 200px; resize: vertical;
    border: none; outline: none; padding: 10px 12px; font: inherit;
    font-size: 13px; color: #111827; box-sizing: border-box;
  }
  .panel .actions {
    display: flex; justify-content: space-between; align-items: center;
    padding: 8px 12px; border-top: 1px solid #f3f4f6; background: #fafbfc;
  }
  .panel .hint { font-size: 10px; color: #9ca3af; }
  .panel .btn {
    border: none; cursor: pointer; padding: 6px 12px; border-radius: 6px;
    font-size: 12px; font-weight: 500;
  }
  .panel .btn.primary { background: #2563eb; color: #fff; }
  .panel .btn.primary:hover { background: #1d4ed8; }
  .panel .btn.primary:disabled { background: #93c5fd; cursor: default; }
  .panel .btn.ghost { background: transparent; color: #6b7280; }
  .panel .btn.ghost:hover { color: #111827; }
  .panel .status { font-size: 11px; color: #6b7280; }
  .panel .status.err { color: #b91c1c; }
  .panel .status.ok  { color: #047857; }
`;

function define() {
  if (typeof customElements === 'undefined' || customElements === null) return;
  if (customElements.get(HOST_TAG)) return;
  class MairuSelectionPrompt extends HTMLElement {
    connectedCallback() {
      if (this._shadow) return;
      const root = this.attachShadow({ mode: 'closed' });
      root.innerHTML = `<style>${STYLE}</style><div class="container"></div>`;
      this._root = root;
      this._container = root.querySelector('.container');
      this._shadow = true;
    }
    setContent(node) {
      if (!this._container) return;
      this._container.replaceChildren(node);
    }
    clear() {
      if (this._container) this._container.replaceChildren();
    }
    _testShadow() { return this._root; }
  }
  customElements.define(HOST_TAG, MairuSelectionPrompt);
}

function clamp(n, min, max) { return Math.max(min, Math.min(max, n)); }

function positionNear(host, rect) {
  const scrollX = window.scrollX || window.pageXOffset || 0;
  const scrollY = window.scrollY || window.pageYOffset || 0;
  const desiredWidth = 340; // wider than panel for safety
  const top = scrollY + rect.bottom + 8;
  const left = clamp(
    scrollX + rect.left,
    scrollX + 8,
    scrollX + Math.max(8, (window.innerWidth || document.documentElement.clientWidth) - desiredWidth - 8),
  );
  host.style.top = `${Math.round(top)}px`;
  host.style.left = `${Math.round(left)}px`;
}

function getSelectionInfo() {
  const sel = window.getSelection ? window.getSelection() : null;
  if (!sel || sel.rangeCount === 0 || sel.isCollapsed) return null;
  const text = sel.toString();
  if (!text || text.trim().length < MIN_SELECTION_LEN) return null;
  let rect = null;
  try {
    rect = sel.getRangeAt(0).getBoundingClientRect();
  } catch (err) { void err; }
  if (!rect || (rect.width === 0 && rect.height === 0)) return null;
  return { text, rect };
}
function installSelectionPrompt(doc = document, opts = {}) {
  define();
  const onSubmit = typeof opts.onSubmit === 'function' ? opts.onSubmit : async () => ({ ok: true });

  let host = doc.querySelector(HOST_TAG);
  if (!host) {
    host = doc.createElement(HOST_TAG);
    host.style.position = 'absolute';
    host.style.top = '-9999px';
    host.style.left = '-9999px';
    (doc.documentElement || doc.body).appendChild(host);
  }

  let lastSelection = null; // {text, rect}
  let mode = 'hidden';      // 'hidden' | 'pill' | 'panel'

  function hide() {
    mode = 'hidden';
    host.clear && host.clear();
    host.style.top = '-9999px';
    host.style.left = '-9999px';
  }

  function showPill(info) {
    mode = 'pill';
    lastSelection = info;
    const btn = doc.createElement('button');
    btn.className = 'pill';
    btn.type = 'button';
    btn.textContent = 'Ask Mairu';
    btn.addEventListener('mousedown', (e) => {
      // Prevent the click from collapsing the selection before we read it.
      e.preventDefault();
    });
    btn.addEventListener('click', () => showPanel(lastSelection));
    host.setContent(btn);
    positionNear(host, info.rect);
  }

  function showPanel(info) {
    mode = 'panel';
    lastSelection = info;

    const panel = doc.createElement('div');
    panel.className = 'panel';

    const header = doc.createElement('header');
    header.innerHTML = `<span>Ask Mairu about selection</span>`;
    const closeBtn = doc.createElement('button');
    closeBtn.type = 'button';
    closeBtn.setAttribute('aria-label', 'Close');
    closeBtn.textContent = '×';
    closeBtn.addEventListener('click', hide);
    header.appendChild(closeBtn);

    const preview = doc.createElement('div');
    preview.className = 'preview';
    preview.textContent = info.text.length > MAX_PREVIEW_LEN
      ? info.text.slice(0, MAX_PREVIEW_LEN) + '…'
      : info.text;

    const textarea = doc.createElement('textarea');
    textarea.placeholder = 'Type a prompt — e.g. "summarise", "explain in plain English", "save as a memory"…';
    textarea.setAttribute('aria-label', 'Prompt for Mairu agent');

    const actions = doc.createElement('div');
    actions.className = 'actions';
    const status = doc.createElement('span');
    status.className = 'status';
    status.textContent = '';
    const right = doc.createElement('div');
    right.style.display = 'flex';
    right.style.gap = '6px';
    const cancel = doc.createElement('button');
    cancel.className = 'btn ghost';
    cancel.type = 'button';
    cancel.textContent = 'Cancel';
    cancel.addEventListener('click', hide);
    const send = doc.createElement('button');
    send.className = 'btn primary';
    send.type = 'button';
    send.textContent = 'Send';

    async function submit() {
      const prompt = textarea.value.trim();
      send.disabled = true;
      status.classList.remove('err', 'ok');
      status.textContent = 'Sending…';
      try {
        const res = await onSubmit({
          text: info.text,
          prompt,
          url: location.href,
          title: doc.title || '',
        });
        if (res && res.ok) {
          status.classList.add('ok');
          status.textContent = 'Sent to Mairu';
          setTimeout(hide, 900);
        } else {
          status.classList.add('err');
          status.textContent = (res && res.error) || 'Failed to send';
          send.disabled = false;
        }
      } catch (err) {
        status.classList.add('err');
        status.textContent = String(err && err.message ? err.message : err);
        send.disabled = false;
      }
    }
    send.addEventListener('click', submit);
    textarea.addEventListener('keydown', (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'Enter') {
        e.preventDefault();
        submit();
      } else if (e.key === 'Escape') {
        e.preventDefault();
        hide();
      }
    });

    right.appendChild(cancel);
    right.appendChild(send);
    actions.appendChild(status);
    actions.appendChild(right);

    panel.appendChild(header);
    panel.appendChild(preview);
    panel.appendChild(textarea);
    panel.appendChild(actions);

    host.setContent(panel);
    positionNear(host, info.rect);

    // Defer focus so the click that opened the panel doesn't immediately steal it.
    setTimeout(() => textarea.focus(), 0);
  }

  function onSelectionMaybeChanged() {
    if (mode === 'panel') return; // user is composing — don't move the host
    const info = getSelectionInfo();
    if (!info) {
      if (mode === 'pill') hide();
      return;
    }
    showPill(info);
  }

  // Selection finalises on mouseup (text) or keyup (shift+arrow keys etc.).
  doc.addEventListener('mouseup', () => {
    // Wait a tick so getSelection() reflects the final selection.
    setTimeout(onSelectionMaybeChanged, 0);
  }, { passive: true });
  doc.addEventListener('keyup', (e) => {
    if (e.shiftKey || e.key === 'Shift' || e.key.startsWith('Arrow')) {
      setTimeout(onSelectionMaybeChanged, 0);
    }
  }, { passive: true });

  // Dismiss the affordance if the user clicks outside it.
  doc.addEventListener('mousedown', (e) => {
    if (mode === 'hidden') return;
    if (e.composedPath && e.composedPath().includes(host)) return;
    if (mode === 'pill') hide();
    // For panel: only close on explicit Cancel/×/Esc, not arbitrary clicks.
  }, { passive: true });

  return {
    hide,
    _host: host,
    _trigger: onSelectionMaybeChanged,
  };
}


// ==== lib/hydration.js ====
function waitForSpaHydration(doc, { quietMs = 500, hardCapMs = 3000 } = {}) {
  return new Promise((resolve) => {
    let obs;
    let quietTimer;
    const target = (doc && (doc.body || doc.documentElement)) || null;
    const done = (reason) => {
      try { obs && obs.disconnect(); } catch (err) { void err; }
      clearTimeout(quietTimer);
      clearTimeout(hardTimer);
      resolve(reason);
    };
    if (typeof MutationObserver !== 'undefined' && target) {
      obs = new MutationObserver(() => {
        clearTimeout(quietTimer);
        quietTimer = setTimeout(() => done('quiet'), quietMs);
      });
      try { obs.observe(target, { childList: true, subtree: true }); } catch (err) { void err; }
    }
    quietTimer = setTimeout(() => done('quiet'), quietMs);
    const hardTimer = setTimeout(() => done('hardcap'), hardCapMs);
  });
}


// ==== lib/serializer.js ====
function serializeWithBudget(root, { timeBudgetMs = 120, sizeLimit = 2 * 1024 * 1024 } = {}) {
  const start = (typeof performance !== 'undefined' ? performance.now() : Date.now());
  const parts = [];
  let size = 0;
  let truncated = false;

  function now() {
    return typeof performance !== 'undefined' ? performance.now() : Date.now();
  }
  function push(s) {
    if (truncated) return;
    if (size + s.length > sizeLimit) {
      truncated = true;
      return;
    }
    parts.push(s);
    size += s.length;
  }
  function escapeText(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }
  function serNode(node) {
    if (truncated) return;
    if (now() - start > timeBudgetMs) {
      truncated = true;
      return;
    }
    if (node.nodeType === 3) {
      push(escapeText(node.textContent));
      return;
    }
    if (node.nodeType !== 1) return;
    const tag = node.localName;
    if (tag === 'script' || tag === 'style' || tag === 'svg' || tag === 'noscript') {
      push(`<${tag}></${tag}>`);
      return;
    }
    push('<' + tag);
    for (const a of node.attributes) {
      push(` ${a.name}="${a.value.replace(/"/g, '&quot;')}"`);
    }
    push('>');
    if (node.shadowRoot) {
      push('<template shadowrootmode="open">');
      for (const c of node.shadowRoot.childNodes) serNode(c);
      push('</template>');
    }
    for (const c of node.childNodes) serNode(c);
    push(`</${tag}>`);
  }

  serNode(root);
  return { html: parts.join(''), truncated, size };
}


// mairu-ext/extension/content.src.js
// Source for content.js. Run scripts/build-content.mjs to regenerate content.js.
// Page-context traps (console/fetch/XHR/History) are injected via chrome.scripting
// from the service worker (see extension/main-world/traps.js) to satisfy strict CSP.

(function () {
  const MUTATION_DEBOUNCE_MS = 2000;
  const HTML_SIZE_LIMIT = 2 * 1024 * 1024;
  const CAPTURE_TIME_BUDGET_MS = 120;
  const VISUAL_RECT_CAP = 200;
  const MEANINGFUL_ATTRS = new Set([
    'src', 'href', 'value', 'checked', 'selected', 'disabled', 'hidden',
    'aria-expanded', 'aria-selected', 'aria-checked', 'aria-label',
    'aria-labelledby', 'aria-describedby', 'data-state', 'data-active',
  ]);

  let debounceTimer = null;
  let consoleErrors = [];
  let networkErrors = [];
  let dwellStart = Date.now();
  let interactionCount = 0;

  const scheme = location.protocol;
  if (!scheme.startsWith('http')) return;

  let overlay;
  try {
    overlay = installOverlay(document);
  } catch (err) {
    void err;
    overlay = { showThought: () => {}, hideThought: () => {} };
  }

  try {
    installSelectionPrompt(document, {
      onSubmit: ({ text, prompt, url, title }) => new Promise((resolve) => {
        try {
          chrome.runtime.sendMessage(
            { type: 'send_to_agent', payload: { text, prompt, url, title, timestamp: Date.now() } },
            (resp) => {
              if (chrome.runtime.lastError) {
                resolve({ ok: false, error: chrome.runtime.lastError.message });
                return;
              }
              resolve(resp || { ok: false, error: 'No response from extension' });
            },
          );
        } catch (err) {
          resolve({ ok: false, error: String(err && err.message ? err.message : err) });
        }
      }),
    });
  } catch (err) {
    void err;
  }

  window.addEventListener('message', (event) => {
    if (!event.data) return;
    if (event.data.type === '__MAIRU_ERROR') {
      if (!consoleErrors.includes(event.data.error)) {
        consoleErrors.push(event.data.error);
        if (consoleErrors.length > 50) consoleErrors.shift();
      }
    } else if (event.data.type === '__MAIRU_NETWORK_ERROR') {
      if (!networkErrors.includes(event.data.error)) {
        networkErrors.push(event.data.error);
        if (networkErrors.length > 50) networkErrors.shift();
      }
    }
  });

  function extractIframeContent() {
    const iframes = [];
    document.querySelectorAll('iframe').forEach((frame) => {
      const entry = {
        src: frame.src || '',
        title: frame.title || frame.getAttribute('aria-label') || null,
        is_same_origin: false,
        sections: [],
      };
      try {
        const doc = frame.contentDocument;
        if (doc && doc.body) {
          entry.is_same_origin = true;
          entry._html = doc.documentElement.outerHTML.slice(0, 50000);
        }
      } catch (err) {
        void err;
      }
      iframes.push(entry);
    });
    return iframes;
  }

  function captureVisualRects() {
    const out = {};
    const visited = new Set();
    const structural = ['header', 'nav', 'main', 'article', 'aside', 'footer', 'h1', 'h2', 'form', 'button', 'input'];
    const add = (el) => {
      if (Object.keys(out).length >= VISUAL_RECT_CAP) return;
      const sel = getCssSelector(el);
      if (!sel || visited.has(sel)) return;
      visited.add(sel);
      const r = el.getBoundingClientRect();
      if (r.width > 0 && r.height > 0) {
        out[sel] = `x:${Math.round(r.x)},y:${Math.round(r.y)},w:${Math.round(r.width)},h:${Math.round(r.height)}`;
      }
    };
    for (const tag of structural) {
      if (Object.keys(out).length >= VISUAL_RECT_CAP) break;
      for (const el of document.querySelectorAll(tag)) {
        if (Object.keys(out).length >= VISUAL_RECT_CAP) break;
        add(el);
      }
    }
    return out;
  }

  function gatherPageState() {
    const { html, truncated } = serializeWithBudget(document.documentElement, {
      timeBudgetMs: CAPTURE_TIME_BUDGET_MS,
      sizeLimit: HTML_SIZE_LIMIT,
    });
    const selection = window.getSelection().toString();

    let activeEl = document.activeElement;
    while (activeEl && activeEl.shadowRoot && activeEl.shadowRoot.activeElement) {
      activeEl = activeEl.shadowRoot.activeElement;
    }
    const active_element = getCssSelector(activeEl);
    const visual_rects = captureVisualRects();

    return { html, truncated, selection, active_element, visual_rects };
  }

  function captureAndSend() {
    const { html, truncated, selection, active_element, visual_rects } = gatherPageState();

    const storage_state = {};
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        const val = localStorage.getItem(key);
        storage_state[`localStorage[${key}]`] = val.length > 200 ? val.substring(0, 200) + '...' : val;
      }
    } catch (err) { void err; }
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        const val = sessionStorage.getItem(key);
        storage_state[`sessionStorage[${key}]`] = val.length > 200 ? val.substring(0, 200) + '...' : val;
      }
    } catch (err) { void err; }

    const iframes = extractIframeContent();

    try {
      chrome.runtime.sendMessage({
        type: 'page_content',
        payload: {
          url: location.href,
          html,
          truncated,
          timestamp: Date.now(),
          selection: selection || null,
          active_element: active_element || null,
          console_errors: consoleErrors,
          network_errors: networkErrors,
          visual_rects,
          storage_state,
          dwell_ms: Date.now() - dwellStart,
          interaction_count: interactionCount,
          iframes: iframes.map((f) => ({
            src: f.src,
            title: f.title,
            is_same_origin: f.is_same_origin,
            html: f.is_same_origin ? f._html : undefined,
          })),
        },
      }, () => {
        // Swallow any sendResponse channel errors — the SW side may not respond and that's fine.
        void chrome.runtime.lastError;
      });
    } catch (err) {
      // SW may be restarting; next capture will retry.
      void err;
    }
  }

  captureAndSend();

  const observer = new MutationObserver((mutations) => {
    const meaningful = mutations.some((m) => {
      if (m.type === 'childList') return m.addedNodes.length > 0 || m.removedNodes.length > 0;
      if (m.type === 'attributes') return MEANINGFUL_ATTRS.has(m.attributeName);
      return false;
    });
    if (!meaningful) return;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, MUTATION_DEBOUNCE_MS);
  });

  const trackInteraction = () => { interactionCount++; };
  document.addEventListener('click', trackInteraction, { passive: true, capture: true });
  document.addEventListener('keydown', trackInteraction, { passive: true, capture: true });
  document.addEventListener('scroll', trackInteraction, { passive: true, capture: true });

  function captureStateForEval() {
    return gatherPageState();
  }

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'dev_force_eval') {
      sendResponse(captureStateForEval());
      return true;
    }
    if (message.type !== 'execute') return;
    try {
      if (message.command === 'click') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.click();
          sendResponse({ success: true, message: `Clicked ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'fill') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.value = message.value;
          el.dispatchEvent(new Event('input', { bubbles: true }));
          el.dispatchEvent(new Event('change', { bubbles: true }));
          sendResponse({ success: true, message: `Filled ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'highlight') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          const origBorder = el.style.border;
          el.style.border = '3px solid red';
          setTimeout(() => { el.style.border = origBorder; }, 3000);
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          sendResponse({ success: true, message: `Highlighted ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'scroll') {
        const el = message.selector ? querySelectorDeep(document, message.selector) : null;
        if (el) {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          sendResponse({ success: true, message: `Scrolled to ${message.selector}` });
        } else if (message.direction) {
          const amount = message.amount || window.innerHeight * 0.8;
          if (message.direction === 'down') window.scrollBy({ top: amount, behavior: 'smooth' });
          else if (message.direction === 'up') window.scrollBy({ top: -amount, behavior: 'smooth' });
          else if (message.direction === 'top') window.scrollTo({ top: 0, behavior: 'smooth' });
          else if (message.direction === 'bottom') window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
          sendResponse({ success: true, message: `Scrolled ${message.direction}` });
        } else {
          sendResponse({ error: 'No element or direction specified' });
        }
      } else if (message.command === 'navigate') {
        if (message.url) {
          window.location.href = message.url;
          sendResponse({ success: true, message: `Navigating to ${message.url}` });
        } else if (message.back) {
          window.history.back();
          sendResponse({ success: true, message: 'Navigating back' });
        } else {
          sendResponse({ error: 'No URL specified for navigation' });
        }
      } else if (message.command === 'get_text') {
        const el = message.selector ? querySelectorDeep(document, message.selector) : document.body;
        sendResponse({ success: true, text: el ? el.innerText : '' });
      } else if (message.command === 'select_text') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          const range = document.createRange();
          range.selectNodeContents(el);
          const sel = window.getSelection();
          sel.removeAllRanges();
          sel.addRange(range);
          sendResponse({ success: true, message: `Selected text in ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'query') {
        const els = querySelectorAllDeep(document, message.selector || '*', 20);
        const results = els.map((el) => ({
          selector: getCssSelector(el),
          text: el.textContent.trim().slice(0, 100),
          tag: el.tagName.toLowerCase(),
        }));
        sendResponse({ success: true, results });
      } else if (message.command === 'set_storage') {
        try {
          if (message.storage_type === 'sessionStorage') {
            window.sessionStorage.setItem(message.key, message.value);
            sendResponse({ success: true, message: `Set sessionStorage[${message.key}]` });
          } else {
            window.localStorage.setItem(message.key, message.value);
            sendResponse({ success: true, message: `Set localStorage[${message.key}]` });
          }
        } catch (e) {
          sendResponse({ error: `Failed to set storage: ${e.message}` });
        }
      } else if (message.command === 'show_thought') {
        overlay.showThought(message.text);
        sendResponse({ success: true });
      } else if (message.command === 'hide_thought') {
        overlay.hideThought();
        document.querySelectorAll('.__mairu_agent_highlight').forEach((el) => {
          el.classList.remove('__mairu_agent_highlight');
          el.style.outline = el.dataset.origOutline || '';
          el.style.outlineOffset = el.dataset.origOutlineOffset || '';
        });
        sendResponse({ success: true });
      } else if (message.command === 'highlight_thought') {
        document.querySelectorAll('.__mairu_agent_highlight').forEach((el) => {
          el.classList.remove('__mairu_agent_highlight');
          el.style.outline = el.dataset.origOutline || '';
          el.style.outlineOffset = el.dataset.origOutlineOffset || '';
        });
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.classList.add('__mairu_agent_highlight');
          el.dataset.origOutline = el.style.outline;
          el.dataset.origOutlineOffset = el.style.outlineOffset;
          el.style.outline = '3px dashed #4facfe';
          el.style.outlineOffset = '2px';
          if (message.scroll !== false) {
            el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }
          sendResponse({ success: true, message: `Highlighted ${message.selector} for thought` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else {
        sendResponse({ error: `Unknown execute command: ${message.command}` });
      }
    } catch (e) {
      sendResponse({ error: `Execution failed: ${e.message}` });
    }
    return true;
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: Array.from(MEANINGFUL_ATTRS),
  });

  document.addEventListener('selectionchange', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, 1000);
  });

  document.addEventListener('focusin', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, 1000);
  });

  const handleSpaNav = async () => {
    dwellStart = Date.now();
    interactionCount = 0;
    await waitForSpaHydration(document, { quietMs: 500, hardCapMs: 3000 });
    captureAndSend();
  };
  window.addEventListener('__mairu_spa_nav', handleSpaNav);
  window.addEventListener('popstate', handleSpaNav);

  window.addEventListener('unload', () => {
    observer.disconnect();
    clearTimeout(debounceTimer);
    document.removeEventListener('click', trackInteraction, { capture: true });
    document.removeEventListener('keydown', trackInteraction, { capture: true });
    document.removeEventListener('scroll', trackInteraction, { capture: true });
  });
})();
