// GENERATED by scripts/build-content.mjs — do not edit directly.
// Edit content.src.js or lib/*.js and rerun 'bun run build:content'.

// ==== lib/dom.js ====
function getCssSelector(el) {
  if (!el || el.nodeType !== 1) return '';
  const path = [];
  while (el && el.nodeType === 1) {
    if (el.id) {
      path.unshift('#' + cssEscape(el.id));
      break;
    }
    let selector = el.localName;
    let sib = el;
    let nth = 1;
    while ((sib = sib.previousElementSibling)) {
      if (sib.localName === el.localName) nth++;
    }
    if (nth !== 1) selector += `:nth-of-type(${nth})`;
    path.unshift(selector);
    const parent = el.parentNode;
    if (!parent) break;
    // Walk past shadow-root boundaries
    if (parent.host) {
      el = parent.host;
      continue;
    }
    if (parent === parent.ownerDocument) break;
    el = parent;
  }
  return path.join(' > ');
}

function cssEscape(s) {
  if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') return CSS.escape(s);
  return String(s).replace(/[^a-zA-Z0-9_-]/g, (c) => `\\${c}`);
}

function getShadowRoot(el) {
  if (typeof chrome !== 'undefined' && chrome.dom && typeof chrome.dom.openOrClosedShadowRoot === 'function') {
    try { return chrome.dom.openOrClosedShadowRoot(el); } catch (err) { void err; }
  }
  return el.shadowRoot || null;
}
function* walkShadowRoots(root) {
  const stack = [root];
  while (stack.length) {
    const node = stack.pop();
    if (!node || !node.querySelectorAll) continue;
    for (const el of node.querySelectorAll('*')) {
      const sr = getShadowRoot(el);
      if (sr) {
        yield sr;
        stack.push(sr);
      }
    }
  }
}
function querySelectorDeep(root, selector) {
  if (!root) return null;
  if (root.querySelector) {
    const found = root.querySelector(selector);
    if (found) return found;
  }
  for (const r of walkShadowRoots(root)) {
    const hit = r.querySelector(selector);
    if (hit) return hit;
  }
  return null;
}
function querySelectorAllDeep(root, selector, limit = 1000) {
  const out = [];
  const visit = (n) => {
    if (out.length >= limit || !n.querySelectorAll) return;
    for (const el of n.querySelectorAll(selector)) {
      if (out.length >= limit) return;
      out.push(el);
    }
  };
  visit(root);
  for (const r of walkShadowRoots(root)) visit(r);
  return out;
}
function rafBatch(fn) {
  let scheduled = false;
  return function () {
    if (scheduled) return;
    scheduled = true;
    const raf = typeof requestAnimationFrame === 'function' ? requestAnimationFrame : (cb) => setTimeout(cb, 16);
    raf(() => {
      scheduled = false;
      try { fn(); } catch (err) { void err; }
    });
  };
}
function isVisible(el) {
  try {
    const s = getComputedStyle(el);
    return s.display !== 'none' && s.visibility !== 'hidden' && s.opacity !== '0';
  } catch (err) {
    void err;
    return true;
  }
}


// ==== lib/overlay.js ====
const TAG = 'mairu-overlay';
const STYLE = `
  :host { all: initial; position: fixed; bottom: 20px; right: 20px;
          z-index: 2147483647; pointer-events: none;
          font: 14px/1.4 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  .card { max-width: 300px; background: #1e1e1e; color: #fff;
          border: 1px solid #333; border-radius: 8px; padding: 12px 16px;
          box-shadow: 0 4px 12px rgba(0,0,0,0.15);
          opacity: 0; transform: translateY(10px);
          transition: opacity .2s ease, transform .2s ease; }
  .card.visible { opacity: 1; transform: translateY(0); }
  .row { display: flex; align-items: flex-start; gap: 10px; }
  .icon { font-size: 18px; }
`;

function define() {
  if (typeof customElements === 'undefined' || customElements === null) return;
  if (customElements.get(TAG)) return;
  class MairuOverlay extends HTMLElement {
    connectedCallback() {
      if (this._shadow) return;
      const root = this.attachShadow({ mode: 'closed' });
      root.innerHTML = `<style>${STYLE}</style>
        <div class="card"><div class="row"><div class="icon">🤖</div><div class="text"></div></div></div>`;
      this._root = root;
      this._card = root.querySelector('.card');
      this._text = root.querySelector('.text');
      this._shadow = true;
    }
    show(t) {
      if (!this._text) return;
      this._text.textContent = t;
      this._card.classList.add('visible');
    }
    hide() {
      if (!this._card) return;
      this._card.classList.remove('visible');
    }
    // For tests — exposes a shadow node reference without breaking encapsulation in prod.
    _testShadow() {
      return this._root;
    }
  }
  customElements.define(TAG, MairuOverlay);
}
function installOverlay(doc = document) {
  define();
  let el = doc.querySelector(TAG);
  if (!el) {
    el = doc.createElement(TAG);
    (doc.documentElement || doc.body).appendChild(el);
  }
  return {
    showThought: (t) => el.show && el.show(t),
    hideThought: () => el.hide && el.hide(),
    destroy: () => { el.remove(); },
    _element: el,
  };
}


// ==== lib/hydration.js ====
function waitForSpaHydration(doc, { quietMs = 500, hardCapMs = 3000 } = {}) {
  return new Promise((resolve) => {
    let obs;
    let quietTimer;
    const target = (doc && (doc.body || doc.documentElement)) || null;
    const done = (reason) => {
      try { obs && obs.disconnect(); } catch (err) { void err; }
      clearTimeout(quietTimer);
      clearTimeout(hardTimer);
      resolve(reason);
    };
    if (typeof MutationObserver !== 'undefined' && target) {
      obs = new MutationObserver(() => {
        clearTimeout(quietTimer);
        quietTimer = setTimeout(() => done('quiet'), quietMs);
      });
      try { obs.observe(target, { childList: true, subtree: true }); } catch (err) { void err; }
    }
    quietTimer = setTimeout(() => done('quiet'), quietMs);
    const hardTimer = setTimeout(() => done('hardcap'), hardCapMs);
  });
}


// ==== lib/serializer.js ====
function serializeWithBudget(root, { timeBudgetMs = 120, sizeLimit = 2 * 1024 * 1024 } = {}) {
  const start = (typeof performance !== 'undefined' ? performance.now() : Date.now());
  const parts = [];
  let size = 0;
  let truncated = false;

  function now() {
    return typeof performance !== 'undefined' ? performance.now() : Date.now();
  }
  function push(s) {
    if (truncated) return;
    if (size + s.length > sizeLimit) {
      truncated = true;
      return;
    }
    parts.push(s);
    size += s.length;
  }
  function escapeText(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }
  function serNode(node) {
    if (truncated) return;
    if (now() - start > timeBudgetMs) {
      truncated = true;
      return;
    }
    if (node.nodeType === 3) {
      push(escapeText(node.textContent));
      return;
    }
    if (node.nodeType !== 1) return;
    const tag = node.localName;
    if (tag === 'script' || tag === 'style' || tag === 'svg' || tag === 'noscript') {
      push(`<${tag}></${tag}>`);
      return;
    }
    push('<' + tag);
    for (const a of node.attributes) {
      push(` ${a.name}="${a.value.replace(/"/g, '&quot;')}"`);
    }
    push('>');
    if (node.shadowRoot) {
      push('<template shadowrootmode="open">');
      for (const c of node.shadowRoot.childNodes) serNode(c);
      push('</template>');
    }
    for (const c of node.childNodes) serNode(c);
    push(`</${tag}>`);
  }

  serNode(root);
  return { html: parts.join(''), truncated, size };
}


// mairu-ext/extension/content.src.js
// Source for content.js. Run scripts/build-content.mjs to regenerate content.js.
// Page-context traps (console/fetch/XHR/History) are injected via chrome.scripting
// from the service worker (see extension/main-world/traps.js) to satisfy strict CSP.

(function () {
  const MUTATION_DEBOUNCE_MS = 2000;
  const HTML_SIZE_LIMIT = 2 * 1024 * 1024;
  const CAPTURE_TIME_BUDGET_MS = 120;
  const VISUAL_RECT_CAP = 200;
  const MEANINGFUL_ATTRS = new Set([
    'src', 'href', 'value', 'checked', 'selected', 'disabled', 'hidden',
    'aria-expanded', 'aria-selected', 'aria-checked', 'aria-label',
    'aria-labelledby', 'aria-describedby', 'data-state', 'data-active',
  ]);

  let debounceTimer = null;
  let consoleErrors = [];
  let networkErrors = [];
  let dwellStart = Date.now();
  let interactionCount = 0;

  const scheme = location.protocol;
  if (!scheme.startsWith('http')) return;

  let overlay;
  try {
    overlay = installOverlay(document);
  } catch (err) {
    void err;
    overlay = { showThought: () => {}, hideThought: () => {} };
  }

  window.addEventListener('message', (event) => {
    if (!event.data) return;
    if (event.data.type === '__MAIRU_ERROR') {
      if (!consoleErrors.includes(event.data.error)) {
        consoleErrors.push(event.data.error);
        if (consoleErrors.length > 50) consoleErrors.shift();
      }
    } else if (event.data.type === '__MAIRU_NETWORK_ERROR') {
      if (!networkErrors.includes(event.data.error)) {
        networkErrors.push(event.data.error);
        if (networkErrors.length > 50) networkErrors.shift();
      }
    }
  });

  function extractIframeContent() {
    const iframes = [];
    document.querySelectorAll('iframe').forEach((frame) => {
      const entry = {
        src: frame.src || '',
        title: frame.title || frame.getAttribute('aria-label') || null,
        is_same_origin: false,
        sections: [],
      };
      try {
        const doc = frame.contentDocument;
        if (doc && doc.body) {
          entry.is_same_origin = true;
          entry._html = doc.documentElement.outerHTML.slice(0, 50000);
        }
      } catch (err) {
        void err;
      }
      iframes.push(entry);
    });
    return iframes;
  }

  function captureVisualRects() {
    const out = {};
    const visited = new Set();
    const structural = ['header', 'nav', 'main', 'article', 'aside', 'footer', 'h1', 'h2', 'form', 'button', 'input'];
    const add = (el) => {
      if (Object.keys(out).length >= VISUAL_RECT_CAP) return;
      const sel = getCssSelector(el);
      if (!sel || visited.has(sel)) return;
      visited.add(sel);
      const r = el.getBoundingClientRect();
      if (r.width > 0 && r.height > 0) {
        out[sel] = `x:${Math.round(r.x)},y:${Math.round(r.y)},w:${Math.round(r.width)},h:${Math.round(r.height)}`;
      }
    };
    for (const tag of structural) {
      if (Object.keys(out).length >= VISUAL_RECT_CAP) break;
      for (const el of document.querySelectorAll(tag)) {
        if (Object.keys(out).length >= VISUAL_RECT_CAP) break;
        add(el);
      }
    }
    return out;
  }

  function gatherPageState() {
    const { html, truncated } = serializeWithBudget(document.documentElement, {
      timeBudgetMs: CAPTURE_TIME_BUDGET_MS,
      sizeLimit: HTML_SIZE_LIMIT,
    });
    const selection = window.getSelection().toString();

    let activeEl = document.activeElement;
    while (activeEl && activeEl.shadowRoot && activeEl.shadowRoot.activeElement) {
      activeEl = activeEl.shadowRoot.activeElement;
    }
    const active_element = getCssSelector(activeEl);
    const visual_rects = captureVisualRects();

    return { html, truncated, selection, active_element, visual_rects };
  }

  function captureAndSend() {
    const { html, truncated, selection, active_element, visual_rects } = gatherPageState();

    const storage_state = {};
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        const val = localStorage.getItem(key);
        storage_state[`localStorage[${key}]`] = val.length > 200 ? val.substring(0, 200) + '...' : val;
      }
    } catch (err) { void err; }
    try {
      for (let i = 0; i < sessionStorage.length; i++) {
        const key = sessionStorage.key(i);
        const val = sessionStorage.getItem(key);
        storage_state[`sessionStorage[${key}]`] = val.length > 200 ? val.substring(0, 200) + '...' : val;
      }
    } catch (err) { void err; }

    const iframes = extractIframeContent();

    try {
      chrome.runtime.sendMessage({
        type: 'page_content',
        payload: {
          url: location.href,
          html,
          truncated,
          timestamp: Date.now(),
          selection: selection || null,
          active_element: active_element || null,
          console_errors: consoleErrors,
          network_errors: networkErrors,
          visual_rects,
          storage_state,
          dwell_ms: Date.now() - dwellStart,
          interaction_count: interactionCount,
          iframes: iframes.map((f) => ({
            src: f.src,
            title: f.title,
            is_same_origin: f.is_same_origin,
            html: f.is_same_origin ? f._html : undefined,
          })),
        },
      }, () => {
        // Swallow any sendResponse channel errors — the SW side may not respond and that's fine.
        void chrome.runtime.lastError;
      });
    } catch (err) {
      // SW may be restarting; next capture will retry.
      void err;
    }
  }

  captureAndSend();

  const observer = new MutationObserver((mutations) => {
    const meaningful = mutations.some((m) => {
      if (m.type === 'childList') return m.addedNodes.length > 0 || m.removedNodes.length > 0;
      if (m.type === 'attributes') return MEANINGFUL_ATTRS.has(m.attributeName);
      return false;
    });
    if (!meaningful) return;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, MUTATION_DEBOUNCE_MS);
  });

  const trackInteraction = () => { interactionCount++; };
  document.addEventListener('click', trackInteraction, { passive: true, capture: true });
  document.addEventListener('keydown', trackInteraction, { passive: true, capture: true });
  document.addEventListener('scroll', trackInteraction, { passive: true, capture: true });

  function captureStateForEval() {
    return gatherPageState();
  }

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'dev_force_eval') {
      sendResponse(captureStateForEval());
      return true;
    }
    if (message.type !== 'execute') return;
    try {
      if (message.command === 'click') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.click();
          sendResponse({ success: true, message: `Clicked ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'fill') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.value = message.value;
          el.dispatchEvent(new Event('input', { bubbles: true }));
          el.dispatchEvent(new Event('change', { bubbles: true }));
          sendResponse({ success: true, message: `Filled ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'highlight') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          const origBorder = el.style.border;
          el.style.border = '3px solid red';
          setTimeout(() => { el.style.border = origBorder; }, 3000);
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          sendResponse({ success: true, message: `Highlighted ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'scroll') {
        const el = message.selector ? querySelectorDeep(document, message.selector) : null;
        if (el) {
          el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          sendResponse({ success: true, message: `Scrolled to ${message.selector}` });
        } else if (message.direction) {
          const amount = message.amount || window.innerHeight * 0.8;
          if (message.direction === 'down') window.scrollBy({ top: amount, behavior: 'smooth' });
          else if (message.direction === 'up') window.scrollBy({ top: -amount, behavior: 'smooth' });
          else if (message.direction === 'top') window.scrollTo({ top: 0, behavior: 'smooth' });
          else if (message.direction === 'bottom') window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
          sendResponse({ success: true, message: `Scrolled ${message.direction}` });
        } else {
          sendResponse({ error: 'No element or direction specified' });
        }
      } else if (message.command === 'navigate') {
        if (message.url) {
          window.location.href = message.url;
          sendResponse({ success: true, message: `Navigating to ${message.url}` });
        } else if (message.back) {
          window.history.back();
          sendResponse({ success: true, message: 'Navigating back' });
        } else {
          sendResponse({ error: 'No URL specified for navigation' });
        }
      } else if (message.command === 'get_text') {
        const el = message.selector ? querySelectorDeep(document, message.selector) : document.body;
        sendResponse({ success: true, text: el ? el.innerText : '' });
      } else if (message.command === 'select_text') {
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          const range = document.createRange();
          range.selectNodeContents(el);
          const sel = window.getSelection();
          sel.removeAllRanges();
          sel.addRange(range);
          sendResponse({ success: true, message: `Selected text in ${message.selector}` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else if (message.command === 'query') {
        const els = querySelectorAllDeep(document, message.selector || '*', 20);
        const results = els.map((el) => ({
          selector: getCssSelector(el),
          text: el.textContent.trim().slice(0, 100),
          tag: el.tagName.toLowerCase(),
        }));
        sendResponse({ success: true, results });
      } else if (message.command === 'set_storage') {
        try {
          if (message.storage_type === 'sessionStorage') {
            window.sessionStorage.setItem(message.key, message.value);
            sendResponse({ success: true, message: `Set sessionStorage[${message.key}]` });
          } else {
            window.localStorage.setItem(message.key, message.value);
            sendResponse({ success: true, message: `Set localStorage[${message.key}]` });
          }
        } catch (e) {
          sendResponse({ error: `Failed to set storage: ${e.message}` });
        }
      } else if (message.command === 'show_thought') {
        overlay.showThought(message.text);
        sendResponse({ success: true });
      } else if (message.command === 'hide_thought') {
        overlay.hideThought();
        document.querySelectorAll('.__mairu_agent_highlight').forEach((el) => {
          el.classList.remove('__mairu_agent_highlight');
          el.style.outline = el.dataset.origOutline || '';
          el.style.outlineOffset = el.dataset.origOutlineOffset || '';
        });
        sendResponse({ success: true });
      } else if (message.command === 'highlight_thought') {
        document.querySelectorAll('.__mairu_agent_highlight').forEach((el) => {
          el.classList.remove('__mairu_agent_highlight');
          el.style.outline = el.dataset.origOutline || '';
          el.style.outlineOffset = el.dataset.origOutlineOffset || '';
        });
        const el = querySelectorDeep(document, message.selector);
        if (el) {
          el.classList.add('__mairu_agent_highlight');
          el.dataset.origOutline = el.style.outline;
          el.dataset.origOutlineOffset = el.style.outlineOffset;
          el.style.outline = '3px dashed #4facfe';
          el.style.outlineOffset = '2px';
          if (message.scroll !== false) {
            el.scrollIntoView({ behavior: 'smooth', block: 'center' });
          }
          sendResponse({ success: true, message: `Highlighted ${message.selector} for thought` });
        } else {
          sendResponse({ error: `Element not found: ${message.selector}` });
        }
      } else {
        sendResponse({ error: `Unknown execute command: ${message.command}` });
      }
    } catch (e) {
      sendResponse({ error: `Execution failed: ${e.message}` });
    }
    return true;
  });

  observer.observe(document.body, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: Array.from(MEANINGFUL_ATTRS),
  });

  document.addEventListener('selectionchange', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, 1000);
  });

  document.addEventListener('focusin', () => {
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(captureAndSend, 1000);
  });

  const handleSpaNav = async () => {
    dwellStart = Date.now();
    interactionCount = 0;
    await waitForSpaHydration(document, { quietMs: 500, hardCapMs: 3000 });
    captureAndSend();
  };
  window.addEventListener('__mairu_spa_nav', handleSpaNav);
  window.addEventListener('popstate', handleSpaNav);

  window.addEventListener('unload', () => {
    observer.disconnect();
    clearTimeout(debounceTimer);
    document.removeEventListener('click', trackInteraction, { capture: true });
    document.removeEventListener('keydown', trackInteraction, { capture: true });
    document.removeEventListener('scroll', trackInteraction, { capture: true });
  });
})();
