#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""

main() {
  local __xcmd1="git rev-parse --show-toplevel 2>/dev/null"
  __xout2=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr3=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode4=0
  sh -c "$__xcmd1" >"$__xout2" 2>"$__xerr3" || __xcode4=$?
  __ret__code=$__xcode4
  __ret__stdout=$(cat "$__xout2" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr3" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout2" "$__xerr3"
  local __rec5__code="${__ret__code}"
  local __rec5__ok="${__ret__ok}"
  local __rec5__stdout="${__ret__stdout}"
  local __rec5__stderr="${__ret__stderr}"
  local top__code="${__rec5__code}"
  local top__ok="${__rec5__ok}"
  local top__stdout="${__rec5__stdout}"
  local top__stderr="${__rec5__stderr}"
  if ! [ "$top__ok" = 1 ]; then
    printf '%s\n' "check-fixtures: not inside a git repository" 1>&2
    exit 1
  fi
  local __trim_s7="${top__stdout}"
  __trim6=$(__trim_s7="$__trim_s7" awk 'BEGIN { s = ENVIRON["__trim_s7"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local mairuDir="${__trim6}/mairu"
  local __fst_p8="${mairuDir}/go.mod"
  if [ -f "$__fst_p8" ]; then __fst_r9=1; else __fst_r9=0; fi
  __cond10=$((__fst_r9))
  if ! [ "$__cond10" = 1 ]; then
    printf '%s\n' "check-fixtures: cannot find ${mairuDir}/go.mod" 1>&2
    exit 1
  fi
  local __xcmd11="cd \"${mairuDir}\" && go test ./internal/ast/... -run '^TestFixtureCompleteness\$' -count=1"
  __xout12=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr13=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode14=0
  sh -c "$__xcmd11" >"$__xout12" 2>"$__xerr13" || __xcode14=$?
  __ret__code=$__xcode14
  __ret__stdout=$(cat "$__xout12" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr13" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout12" "$__xerr13"
  local __rec15__code="${__ret__code}"
  local __rec15__ok="${__ret__ok}"
  local __rec15__stdout="${__ret__stdout}"
  local __rec15__stderr="${__ret__stderr}"
  local r__code="${__rec15__code}"
  local r__ok="${__rec15__ok}"
  local r__stdout="${__rec15__stdout}"
  local r__stderr="${__rec15__stderr}"
  if [ "${r__stdout}" != "" ]; then
    printf '%s\n' "${r__stdout}"
  fi
  if [ "${r__stderr}" != "" ]; then
    printf '%s\n' "${r__stderr}" 1>&2
  fi
  exit $((r__code))
}


main "$@"
