#!/bin/sh
# Generated by tartalo. Do not edit by hand.
set -eu

__ret=""

main() {
  local __xcmd1="git rev-parse --show-toplevel 2>/dev/null"
  __xout2=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr3=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode4=0
  sh -c "$__xcmd1" >"$__xout2" 2>"$__xerr3" || __xcode4=$?
  __ret__code=$__xcode4
  __ret__stdout=$(cat "$__xout2" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr3" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout2" "$__xerr3"
  local __rec5__code="${__ret__code}"
  local __rec5__ok="${__ret__ok}"
  local __rec5__stdout="${__ret__stdout}"
  local __rec5__stderr="${__ret__stderr}"
  local top__code="${__rec5__code}"
  local top__ok="${__rec5__ok}"
  local top__stdout="${__rec5__stdout}"
  local top__stderr="${__rec5__stderr}"
  if ! [ "$top__ok" = 1 ]; then
    printf '%s\n' "Git hooks directory not found. Run inside a git repository." 1>&2
    exit 1
  fi
  local __trim_s9="${top__stdout}"
  __trim8=$(__trim_s9="$__trim_s9" awk 'BEGIN { s = ENVIRON["__trim_s9"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
  local root="${__trim8}"
  local sourceHook="${root}/.githooks/pre-commit"
  local hooksDir="${root}/.git/hooks"
  local targetHook="${hooksDir}/pre-commit"
  local __fst_p10="${hooksDir}"
  if [ -d "$__fst_p10" ]; then __fst_r11=1; else __fst_r11=0; fi
  __cond12=$((__fst_r11))
  if ! [ "$__cond12" = 1 ]; then
    printf '%s\n' "Git hooks directory not found. Run inside a git repository." 1>&2
    exit 1
  fi
  local __fst_p13="${sourceHook}"
  if [ -f "$__fst_p13" ]; then __fst_r14=1; else __fst_r14=0; fi
  __cond15=$((__fst_r14))
  if ! [ "$__cond15" = 1 ]; then
    printf '%s\n' "Source hook missing: ${sourceHook}" 1>&2
    exit 1
  fi
  local __xcmd16="install -m 0755 \"${sourceHook}\" \"${targetHook}\""
  __xout17=$(mktemp 2>/dev/null || printf '/tmp/tt_o_%s' "$$")
  __xerr18=$(mktemp 2>/dev/null || printf '/tmp/tt_e_%s' "$$")
  local __xcode19=0
  sh -c "$__xcmd16" >"$__xout17" 2>"$__xerr18" || __xcode19=$?
  __ret__code=$__xcode19
  __ret__stdout=$(cat "$__xout17" 2>/dev/null || printf '')
  __ret__stderr=$(cat "$__xerr18" 2>/dev/null || printf '')
  __ret__ok=$(( __ret__code == 0 ))
  rm -f "$__xout17" "$__xerr18"
  local __rec20__code="${__ret__code}"
  local __rec20__ok="${__ret__ok}"
  local __rec20__stdout="${__ret__stdout}"
  local __rec20__stderr="${__ret__stderr}"
  local r__code="${__rec20__code}"
  local r__ok="${__rec20__ok}"
  local r__stdout="${__rec20__stdout}"
  local r__stderr="${__rec20__stderr}"
  if ! [ "$r__ok" = 1 ]; then
    local __trim_s22="${r__stderr}"
    __trim21=$(__trim_s22="$__trim_s22" awk 'BEGIN { s = ENVIRON["__trim_s22"]; sub(/^[ \t\r\n]+/, "", s); sub(/[ \t\r\n]+$/, "", s); printf "%s", s }')
    printf '%s\n' "${__trim21}" 1>&2
    exit $((r__code))
  fi
  printf '%s\n' "Installed pre-commit hook to ${targetHook}"
}


main "$@"
